### ISSUE TITLE
Quality update will break UWP app Windows. 

### ISSUE THREAD

**Issue by IRedDragonICY** [jbara2002/windows-defender-remover#38] opened 2023-04-13 06:26 UTC
Remover Version: [Version 12.3.1](https://github.com/jbara2002/windows-defender-remover/releases/tag/release_def_12_3_1)
Option:  Pressing "Y", Windows Defender will be REMOVED.
Windows version: 
![image](https://user-images.githubusercontent.com/98265563/231671985-7869bb23-d2ce-49ca-98a0-3e01e134fd9d.png)
Before update quality, UWP working fine, but after update it will break some parts in UWP.

![image](https://user-images.githubusercontent.com/98265563/231671655-18c24a8b-7a96-43e2-bb9a-d2c1c8eff8e7.png)

**Comment by jbara2002** [comment] 2023-04-13 07:23
its look like Moment 3 is breaking the script. I will test into moment 3 VM and i try to find the problem. thx for noticing.

**Comment by jbara2002** [comment] 2023-04-13 18:40
Update:
For me  i didn't see any problem or a bug. So the error which you get will be from Microsoft Photos.. You can try update that in Microsoft Store.

**Comment by IRedDragonICY** [comment] 2023-04-13 19:16
not only Microsoft Photos, all UWP Apps and Microsoft store cannot open.

**Comment by jbara2002** [comment] 2023-04-13 20:35
i will wait for next quality update for moment 3, for now all things are ok. i didn't see the bug. do you have something info. in event log about the uwp. it helps to troubleshoot much easier

**Comment by IRedDragonICY** [comment] 2023-04-14 21:17
Well, I've done a clean install. I'm sorry that I can't generate logs for you. If any problems persist, I will report them to you.

**Comment by IRedDragonICY** [comment] 2023-04-15 04:00
Here logs from EventViewer , maybe something usefull. I'm think i'll change to disable option, it's more stable.
[Logs](https://github.com/jbara2002/windows-defender-remover/files/11238228/Downloads.zip)
![image](https://user-images.githubusercontent.com/98265563/232181855-1d313d83-f7e0-4860-859d-d38fdc72b0a5.png)

**Comment by SCM1981** [comment] 2023-04-18 17:07
Hello, this issue re-appear with version 12.4.
I am using Windows 11 and removed defender with "Y"
Installed UWPs and Microsoft Store working but apps not deleting nor updating.
![image](https://user-images.githubusercontent.com/60676540/232852184-84f594d1-46b3-46c2-aaa9-e4a473a9308a.png)

**Comment by NeatWolf** [comment] 2023-04-30 04:32
Same issue here. Progressively all apps installed using Windows Store get broken when updating.
Then, Windows Store itself gets broken.
After a few days I spent trying to "fix" this and the Security Centre - now the System Settings are broken (!)
Any powershell magic or advice is welcome as I really wasn't going to re-install or repair windows anytime soon.
I thought it was a "me" problem, but it obviously isn't as other people's reporting the very same issues: somehow the tool, when disabling the security centre, indirectly affects the way UWP applications gets updated, causing a chain corruption of the OS (in my experience).

The options the tool provides to re-enable the features don't seem to work.

**Comment by jbara2002** [comment] 2023-04-30 08:30
@NeatWolf  can you specify what version of Windows (10/11) and the code of the update (KBxxxxxxxx) you've applied?

**Comment by jbara2002** [comment] 2023-05-05 06:32
update: this uwp issue is caused by unregistering classes of windows smart screen, so that is needed for uwp functionality (sometimes). The class which i'm talking about is ``` SmartScreen Settings Checker ```. The next version of Defender Remover will not unregister SmartScreen anymore.

**Comment by jbara2002** [comment] 2023-05-05 14:40
fixed in 12.4.1

**Closed by jbara2002** 2023-05-05 14:40 UTC
