### ISSUE TITLE
Task Manager changed

### ISSUE THREAD

**Issue by Sivart-Williamsson** [jbara2002/windows-defender-remover#34] opened 2023-03-16 04:55 UTC
After using the tool to remove defender my Task Manger reverted to a much older version 
![1 Before removing Defender](https://user-images.githubusercontent.com/128016334/225517225-46834f44-0a72-42a7-a096-a6d8110c2cae.jpg)
![2 After Removing Defender](https://user-images.githubusercontent.com/128016334/225517257-2d64f18c-8452-4acf-acec-fc0aeecff550.jpg)
Also some of my app defaults were reset and Radeon software suite did not run on boot up it had to be manually started after boot up. I am running window 11 22h2 build 22621.1413. Is their a way to restore my Task Manger? Other than that it did remove Defender...

**Comment by jbara2002** [comment] 2023-03-16 11:24
Thanks for noticing! I'll investigate if this caused by the script.

**Comment by jbara2002** [comment] 2023-03-20 13:09
provided fix for uwp startup but, for task manager its still investigating..

**Comment by jbara2002** [comment] 2023-04-01 06:41
fixed in 12.3

**Closed by jbara2002** 2023-04-01 06:41 UTC
Labels: bug
