### ISSUE TITLE
Unable to apply Windows updates after June 2022

### ISSUE THREAD

**Issue by SupLiCatinG** [jbara2002/windows-defender-remover#8] opened 2022-09-19 14:53 UTC
I'm using 22H2, especially this issue appeared in June updates, everytime when i want to update i need to re-install Windows. Manual .msu packages doesnt work either.

**Comment by SupLiCatinG** [comment] 2022-09-19 14:58
![image](https://user-images.githubusercontent.com/94017480/191048436-046d4752-6eaf-4c5b-9f42-37cc23915604.png)

**Comment by jbara2002** [comment] 2022-09-19 17:04
Hi. You have the problem because defender is removed from Windows Package List, and applying some updates it get an error The Package cannot be found.  But you showed the code of the error. The error 0x800f081f, commonly means that the update requires the .Net Framework 3.5 to be installed. So, proceed and install Net Framework 3.5, in order to solve the KB 5017308 installation error 0x800f081f. Retry the installation. If the error persists, it caused by Windows-Defender Package.

**Comment by SupLiCatinG** [comment] 2022-09-19 17:22
Does applying script removes Net Framework 3.5 from system ? Because when i installed windows i installed immediately net framework packages.

**Comment by jbara2002** [comment] 2022-09-19 17:50
No.
The Script is removing Windows Defender Package (WinDef Service + Windows Security App & control panel applet) from The System, The Sense Package (Windows Defender with Advanced Protection) and some Windows HVSI (Windows Virtualization Services, including Core Isolation ). 
Windows has a list of the packages which they are indexed. There indexed can be found in C:\Windows\System32\CatRoot (*.cat files).
The error 0x800f081f is caused by a package which cannot be found in the system such as Windows-Defender or Microsoft-Windows-HVSI or Microsoft-Windows-Sense  (Windows Defender with Advanced Protection) package. I will test the forcing removing and disable, but was sometimes, until i fix.  
It looks like Microsoft is Updating Defender Services, that's why you get the error.

**Comment by BurntDog** [comment] 2022-09-19 20:47
When I had issues updating Windows 10 it refused to update and even my pause option was disabled.
I had to reinstall this ----> "Windows10Upgrade9252.exe" and that fixed my issue. Of course just like after so many updates
I was forced to reinstall my audio drivers and Nahimic panel and even my NVidia control panel at times. That's Windows for ya.

**Comment by jbara2002** [comment] 2022-09-24 19:10
The Update problem is fixed in Version 11!

**Closed by jbara2002** 2022-09-24 19:10 UTC
