### ISSUE TITLE
Fail with virtualization softwares

### ISSUE THREAD

**Issue by MoreiraCristiano** [jbara2002/windows-defender-remover#7] opened 2022-09-18 01:52 UTC
Hi, this is a very nice app but after uninstall defender, i cant virtualize with virtualbox (i think is not a bug, because have a reg entry about virtualization). 
How can I virtualize now?

**Comment by jbara2002** [comment] 2022-09-18 09:27
I'll keep an eye on this issue. Thanks for noticing.

**Comment by MoreiraCristiano** [comment] 2022-09-18 11:32
![Captura de tela 2022-09-18 083121](https://user-images.githubusercontent.com/76622857/190899924-a720fc50-2de5-4736-af53-9e81b92a7fa9.png)

**Comment by MoreiraCristiano** [comment] 2022-09-18 11:34
I tryed to restore my windows, withouth formatting, and the issue is the same

**Comment by jbara2002** [comment] 2022-09-18 15:26
I see.. In previous versions of the script the problems are with Hyper-V, because i am confused with Hyper-V Containers (used with LXSS (Linux SubSystem), with Defender Container .wim (Removal of the Windows Defender Offline Scan .wim file). I made workaraounds and the problem was solved. Now, the problem is moved into Virtual Box, I've tested with VMware and Windows 11 22H2 and i don't have any problems. Until the remover part is fixed, you can use disabler part (is reversebile via script, where the remover is affecting the entire system package).

**Comment by MoreiraCristiano** [comment] 2022-09-18 15:52
Ok, anyway your software is powerfull and great. I think you only need to add this kind of issues on readme, to people know before install.
Some softwares, like Kaspersky, need virtualization active to working well. (I do not know exactly why).
Actually, I just format my pc and now its all ok. I
I am using "df control", if you want to see: https://www.sordum.org/9480/defender-control-v2-1/.
Thanks for your help!

**Comment by jbara2002** [comment] 2022-09-24 19:09
The Virtualization problem is fixed in Version 11!

**Closed by jbara2002** 2022-09-24 19:09 UTC
